In [20]:
import numpy as np

In [21]:
-np.pmt(0.05/12,12,1000000)

85607.48178846746

355.21776675711635

In [23]:
y=-np.ppmt(0.05/12,12,12,1000000)
y

85252.26402171033

In [24]:
x+y

85607.48178846746

In [29]:
np.ipmt(0.05/12,12,12,1000000)

array(-355.21776676)

In [27]:
np.ppmt(0.05/12,12,12,1000000)

-85252.26402171033

In [30]:
per = np.arange(1*12) + 1

In [31]:
per

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
principal = 2500.00
np.ipmt(0.0824/12, 1, 1*12, principal)

array(-17.16666667)

In [37]:
-np.ppmt(0.0824/12,per,12,1000000)

array([80232.76947471, 80783.70115844, 81338.41590639, 81896.93969562,
       82459.29868153, 83025.51919914, 83595.62776431, 84169.65107496,
       84747.61601234, 85329.54964229, 85915.4792165 , 86505.43217379])

In [38]:
-np.ipmt(0.0824/12, per, 1*12, principal)

array([17.16666667, 15.78933746, 14.40255059, 13.00624111, 11.60034365,
       10.18479236,  8.75952094,  7.32446267,  5.87955032,  4.42471625,
        2.95989231,  1.48500992])